squidGuard 1.5 beta 20100909

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -19,7 +19,7 @@ AC_PATH_PROG(PERL,perl,no,$PATH:/usr/bin:/usr/local/bin/:/local/bin:/local/perl/
 if test $PERL = no; then
 	echo
 	echo "** No Perl found in the PATH. Perl is required"
-	echo "   for blocked.cgi to work "
+	echo "   for squidGuard.cgi to work "
 	echo 
 fi
 
@@ -31,12 +31,16 @@ sg_config=/usr/local/squidGuard/squidGuard.conf
 sg_dbhome=/usr/local/squidGuard/db
 sg_logdir=/usr/local/squidGuard/log
 sg_cfgdir=/usr/local/squidGuard
+syslog_facility=LOCAL4
 dbprefix=/usr/local
+ldapprefix=/usr
 
 default_directory="/usr /usr/local"
 
 db_lib=-L$dbprefix/BerkeleyDB/lib
 db_inc=-I$dbprefix/BerkeleyDB/include
+ldap_lib=-L$ldapprefix/lib
+ldap_inc=-I$ldapprefix/include
 
 AC_DEFUN(FAIL_MESSAGE,[
    echo
@@ -86,32 +90,50 @@ AC_ARG_WITH(sg_dbhome,
 
 AC_ARG_WITH(nolog,
  	[  --with-nolog=ARG        supress logging except for start and stop messages (default: ARG=no)],
-	nolog=$withval )
+	        nolog=$withval )
+
+AC_ARG_WITH(syslog,
+	[  --with-syslog=ARG       send log messages to syslog for logging (default: ARG=no)],
+	        syslog=$withval )
+
+AC_ARG_WITH(syslog_facility,
+        [  --with-syslog-facility=FAC   use FAC as syslog facility (default: FAC=LOCAL4)],
+                syslog_facility=$withval )
 
 AC_ARG_WITH(squiduser,
         [  --with-squiduser=USER   do set squid user to USER (default: squid)],
 	     squiduser=$withval)
 
+AC_ARG_WITH(ldap, AC_HELP_STRING([--with-ldap], [use ldap for authentication (default: no ldap)]))
+
+AC_ARG_WITH(ldap_lib,
+        [  --with-ldap-lib=DIR     location of the LDAP library],
+                [ldap_lib="-L${withval}"])
+
+AC_ARG_WITH(ldap_inc,
+        [  --with-ldap-inc=DIR     location of the LDAP include files],
+                [ldap_inc="-I${withval}"])
+
+
 if test -n "$sg_config"; then
-	AC_DEFINE(ACCONFIG)
+	AC_DEFINE(ACCONFIG, 1, [Defined if you supply --with-sg-config])
 changequote(, )dnl
 	sg_cfgdir=`echo $sg_config|sed "s%/[^/][^/]*$%%"`
 changequote([, ])dnl
 fi
 
 if test -n "$sg_logdir"; then
-	AC_DEFINE(ACLOGDIR)
+	AC_DEFINE(ACLOGDIR, 1, [Defined if you supply --with-sg-logdir])
 fi
 
 if test -n "$sg_dbhome"; then
-	AC_DEFINE(ACDBHOME)
+	AC_DEFINE(ACDBHOME, 1, [Defined if you supply --with-sg-dbhome])
 fi
 
-CFLAGS="$CFLAGS $db_inc"
-CXXFLAGS="$CXXFLAGS $db_inc"
-CPPFLAGS="$CPPFLAGS $db_inc"
-LDFLAGS="$LDFLAGS $db_lib"
-
+CFLAGS="$CFLAGS $db_inc $ldap_inc"
+CXXFLAGS="$CXXFLAGS $db_inc $ldap_inc"
+CPPFLAGS="$CPPFLAGS $db_inc $ldap_inc"
+LDFLAGS="$LDFLAGS $db_lib $ldap_lib"
 
 dnl
 dnl Checks for header files.
@@ -141,7 +163,7 @@ if test $HAVE_REGEX.H = no; then
 fi
 
 dnl
-dnl Checks if runtime logmessages shall be suppressed. Is --nolog given?
+dnl Checks if runtime logmessages shall be suppressed. 
 dnl
 AC_ARG_WITH(nolog)
 if test "$nolog" = "yes" -o "$nolog" = "true"; then
@@ -150,6 +172,27 @@ NOLOG1="/* nolog option set:"
 NOLOG2="*/"
 else
 echo "checking suppress runtime logging... no"
+fi
+
+dnl
+dnl Checks if logmessages shall be send to syslog.
+dnl
+AC_ARG_WITH(syslog)
+if test "$syslog" = "yes" -o "$syslog" = "true"; then
+AC_CHECK_HEADER(syslog.h,,[
+        echo
+        echo "** No syslog.h found"
+        echo "   You cannot use syslog for logging."
+        echo
+        exit 1
+       ])
+echo "checking syslog for logging... yes"
+LOGFAC="$syslog_facility"
+AC_DEFINE(USE_SYSLOG, 1, [Defined if SYSLOG support should be compiled])
+else
+NOSYSLOG1="/* syslog not configured"
+NOSYSLOG2="*/"
+echo "checking syslog for logging... no"
 fi
 
 dnl
@@ -167,15 +210,14 @@ dnl Checks for libraries. Do in least-dependent to most-dependent order.
 dnl
 
 dnl Check ldap
-AC_ARG_WITH(ldap,
-  AC_HELP_STRING([--with-ldap], [use ldap (default: no ldap)]))
 if test "$with_ldap" = "yes" -o "$with_ldap" = "true"; then
   AC_CHECK_LIB( ldap, ldap_init,
        [
 	echo "checking for ldap support... yes"
 	with_ldap=yes
-	LIBS="$LIBS -lldap"
-	YACCLINE="                     | LDAPUSERSEARCH WORD { sgSourceLdapUserSearch(\$2); }"
+	LIBS="$LIBS -lldap $ldap_lib"
+	YACCLINE="                     | LDAPUSERSEARCH STRING { sgSourceLdapUserSearch(\$2); }"
+	YACCLINE2="                     | LDAPIPSEARCH WORD { sgSourceLdapIpSearch(\$2); }"
        ],[
        AC_MSG_WARN([Cannot find LDAP libraries. LDAP support disabled])
        with_ldap=no
@@ -184,9 +226,10 @@ else
 	echo "checking for ldap support... no"
 	with_ldap=no
 	YACCLINE=""
+	YACCLINE2=""
 fi
 if test "$with_ldap" = "yes"; then
-       AC_DEFINE(HAVE_LIBLDAP)
+       AC_DEFINE(HAVE_LIBLDAP, 1, [Define if LDAP support should be compiled])
        AC_RUN_IFELSE([
 
        #include <ldap.h>
@@ -201,7 +244,9 @@ if test "$with_ldap" = "yes"; then
                echo "Unable to link to LDAP library."
                echo
                exit 1
-       ],)
+       ],[
+               ac_status=0
+       ])
 fi
 
 dnl
@@ -277,7 +322,7 @@ if test "$with_mysql" != "no"; then
       CPPFLAGS="${CPPFLAGS} -I${MYSQL_INC_DIR}"
       AC_CHECK_LIB(z, compress)
       LIBS="-lmysqlclient ${LIBS}"
-      AC_DEFINE(HAVE_MYSQL)
+      AC_DEFINE(HAVE_MYSQL, 1, [Define if MySQL support should be compiled])
     fi
   fi
 else
@@ -314,7 +359,7 @@ AC_RUN_IFELSE([
 			exit (0);
 		exit (1);
 	}	
-	], db_ok_version=yes, db_ok_version=no, db_ok_version=no)
+	], db_ok_version=yes, db_ok_version=no, db_ok_version=yes)
 
 if test $db_ok_version = no; then
 	echo
@@ -345,7 +390,7 @@ AC_RUN_IFELSE([
 			exit (1);
 		exit (0);
 	}	
-	], db_ok_version=yes, db_ok_version=no, db_ok_version=no)
+	], db_ok_version=yes, db_ok_version=no, db_ok_version=yes)
 
 if test $db_ok_version = no; then
 	echo
@@ -377,10 +422,10 @@ AC_RUN_IFELSE([
 			exit (0);
 		exit (1);
 	}	
-	], dbg2_ok_version=yes, dbg2_ok_version=no, dbg2_ok_version=no)
+	], dbg2_ok_version=yes, dbg2_ok_version=no, dbg2_ok_version=yes)
 
 if test $dbg2_ok_version = yes; then
-	AC_DEFINE(DB_VERSION_GT2)
+	AC_DEFINE(DB_VERSION_GT2, 1, [Define if you have dbversion greater than 3.2])
 fi
 
 AC_RUN_IFELSE([
@@ -401,10 +446,10 @@ AC_RUN_IFELSE([
                         exit (0);
                 exit (1);
         }
-        ], dbg3_ok_version=yes, dbg3_ok_version=no, dbg3_ok_version=no)
+        ], dbg3_ok_version=yes, dbg3_ok_version=no, dbg3_ok_version=yes)
 
 if test $dbg3_ok_version = yes; then
-        AC_DEFINE(DB_VERSION_GT3)
+        AC_DEFINE(DB_VERSION_GT3, 1, [Define if you have dbversion greater than 4.0])
 fi
 
 
@@ -421,30 +466,13 @@ AC_CHECK_FUNCS(regerror, , AC_MSG_ERROR([No regerror library function.]))
 AC_CHECK_FUNCS(regexec, , AC_MSG_ERROR([No regexec library function.]))
 AC_CHECK_FUNCS(strdup, , AC_MSG_ERROR([No strdup library function.]))
 AC_CHECK_FUNCS(strerror, , AC_MSG_ERROR([No strerror library function.]))
-AC_CHECK_FUNCS(vsprintf, , AC_MSG_ERROR([No vsprintf library function.]))
+AC_CHECK_FUNCS(vsnprintf, , AC_MSG_ERROR([No vsnprintf library function.]))
 AC_CHECK_FUNCS(sigaction)
 AC_CHECK_FUNCS(signal)
 
 
-
-
 VERSION=`pwd | sed 's%.*/squidGuard-%%'`
 TESTDIR="`pwd`/test"
-
-if test -f /bin/csh -a -f /bin/hostname -a -f /bin/domainname; then
-	if test "`/bin/domainname`" = .ost.eltele.no -o "`/bin/domainname`" = .teledanmark.no; then
-		FTPDIR="~ftp/pub/www/proxy/squidGuard"
-		FTPDIR=`/bin/csh -fc "test -d $FTPDIR && echo $FTPDIR" 2>/dev/null | grep -v '^~'` || FTPDIR="@FTPDIR@"
-		CGIFILE="~ftp/pub/www/proxy/squidGuard/contrib/squidGuard.cgi"
-		CGIFILE=`/bin/csh -fc "test -f $CGIFILE && echo $CGIFILE" 2>/dev/null | grep -v '^~'` || CGI="@CGI@"
-		SQUIDGUARDROBOT="~proxy/filter/robot/bin/squidGuardRobot"
-		SQUIDGUARDROBOT=`/bin/csh -fc "test -f $SQUIDGUARDROBOT && echo $SQUIDGUARDROBOT" 2>/dev/null | grep -v '^~'` || SQUIDGUARDROBOT="@SQUIDGUARDROBOT@"
-		SQUIDGUARDROBOTUA="~proxy/filter/robot/lib/RobotUserAgent.pm"
-		SQUIDGUARDROBOTUA=`/bin/csh -fc "test -f $SQUIDGUARDROBOT && echo $SQUIDGUARDROBOTUA" 2>/dev/null | grep -v '^~'` || SQUIDGUARDROBOTUA="@SQUIDGUARDROBOTUA@"
-		BLACKLISTS="$FTPDIR/contrib/blacklists.tar.gz"
-		BLACKLISTS=`/bin/csh -fc "test -f $BLACKLISTS && echo $BLACKLISTS" 2>/dev/null | grep -v '^~'` || BLACKLISTS="@BLACKLISTS@"
-	fi
-fi
 
 
 AC_SUBST(ac_n)
@@ -455,7 +483,11 @@ AC_SUBST(sg_logdir)
 AC_SUBST(sg_dbhome)
 AC_SUBST(NOLOG1)
 AC_SUBST(NOLOG2)
+AC_SUBST(NOSYSLOG1)
+AC_SUBST(NOSYSLOG2)
+AC_SUBST(LOGFAC)
 AC_SUBST(YACCLINE)
+AC_SUBST(YACCLINE2)
 AC_SUBST(MYSQLLINE)
 AC_SUBST(squiduser)
 AC_SUBST(VERSION)
@@ -469,4 +501,4 @@ AC_SUBST(SQUIDGUARDROBOTUA)
 AC_SUBST(ROBOTEXCEPTIONS)
 AC_SUBST(BLACKLISTS)
 
-AC_OUTPUT(Makefile src/Makefile src/sgDiv.c src/sg.h src/sg.y test/Makefile test/test1.conf test/test2.conf samples/Makefile samples/sample.conf samples/squidGuard.cgi samples/squidGuard-simple.cgi samples/squidGuard-simple-de.cgi contrib/Makefile contrib/squidGuardRobot/squidGuardRobot contrib/sgclean/sgclean contrib/hostbyname/hostbyname)
+AC_OUTPUT(Makefile src/Makefile src/main.c src/sgLog.c src/sgDiv.c src/sg.h src/sg.y test/Makefile test/test1.conf test/test2.conf samples/Makefile samples/sample.conf samples/squidGuard.cgi samples/squidGuard-simple.cgi samples/squidGuard-simple-de.cgi contrib/Makefile contrib/squidGuardRobot/squidGuardRobot contrib/sgclean/sgclean contrib/hostbyname/hostbyname)
